import { colors } from "./colors";

export const modes = {
  light: {
    primary: colors.blue[600],
    primaryHover: colors.blue[700],
    primaryDimmed: colors.blue[100],
    success: colors.green[600],
    successStrong: colors.green[700],
    successDimmed: colors.green[50],
    warning: colors.amber[500],
    warningStrong: colors.amber[600],
    warningDimmed: colors.amber[50],
    error: colors.red[600],
    errorStrong: colors.red[700],
    errorDimmed: colors.red[50],
    neutral: colors.slate[300],
    neutralStrong: colors.slate[500],
    neutralDimmed: colors.slate[100],
    text: colors.slate[700],
    textDisabled: colors.slate[400],
    link: colors.blue[600],
    linkHover: colors.blue[700],
    bgPage: colors.slate[100],
    bgSurface: colors.slate[50],
    bgDisabled: colors.slate[200],
    divider: colors.slate[300],
    dividerStrong: colors.slate[400],
    button: {
      primary: colors.blue[600],
      primaryHover: colors.blue[700],
      primaryPressed: colors.blue[800],
      secondary: colors.slate[50],
      secondaryLabel: colors.slate[800],
      subtle: colors.slate[50],
      subtleHover: colors.blue[100],
      subtlePressed: colors.blue[200],
      subtleBorder: colors.slate[300],
      subtleLabel: colors.blue[600],
    },
  },
  dark: {
    primary: colors.blue[400],
    primaryHover: colors.blue[300],
    primaryDimmed: colors.blue[700],
    success: colors.green[400],
    successStrong: colors.green[300],
    successDimmed: colors.green[700],
    warning: colors.amber[400],
    warningStrong: colors.amber[300],
    warningDimmed: colors.amber[700],
    error: colors.red[400],
    errorStrong: colors.red[300],
    errorDimmed: colors.red[700],
    neutral: colors.slate[600],
    neutralStrong: colors.slate[500],
    neutralDimmed: colors.slate[700],
    text: colors.slate[200],
    textDisabled: colors.slate[500],
    link: colors.blue[400],
    linkHover: colors.blue[300],
    bgPage: colors.slate[900],
    bgSurface: colors.slate[800],
    bgDisabled: colors.slate[700],
    divider: colors.slate[700],
    dividerStrong: colors.slate[600],
    button: {
      primary: colors.blue[400],
      primaryHover: colors.blue[300],
      primaryPressed: colors.blue[200],
      secondary: colors.slate[800],
      secondaryLabel: colors.slate[200],
      subtle: colors.slate[800],
      subtleHover: colors.slate[700],
      subtlePressed: colors.slate[600],
      subtleBorder: colors.slate[700],
      subtleLabel: colors.blue[400],
    },
  },
};
