import { createBaseTheme } from "../theme";
import { colors } from "../tokens";

export const ds5 = createBaseTheme((theme) => ({
  name: "ds5",
  colors: {
    modes: {
      dawn: {
        type: "light",
        backgroundColor: colors.light.atmo2,
        containerBackgroundHover: colors.light.primary_20,
        ...colors.common,
        ...colors.light,
      },
      wicked: {
        type: "dark",
        backgroundColor: colors.dark.atmo2,
        containerBackgroundHover: colors.dark.primary_20,
        ...colors.common,
        ...colors.dark,
      },
    },
  },
  typography: {
    display: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.xl4,
      lineHeight: theme.lineHeight.xl4,
    },
    title1: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.xl3,
      lineHeight: theme.lineHeight.xl3,
    },
    title2: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.xl2,
      lineHeight: theme.lineHeight.xl2,
    },
    title3: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.xl,
      lineHeight: theme.lineHeight.xl,
    },
    title4: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.lg,
      lineHeight: theme.lineHeight.lg,
    },
    label: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.base,
      lineHeight: theme.lineHeight.base,
    },
    body: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.normal,
      fontSize: theme.fontSize.base,
      lineHeight: theme.lineHeight.base,
    },
    captionLabel: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.semibold,
      fontSize: theme.fontSize.sm,
      lineHeight: theme.lineHeight.sm,
    },
    caption1: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.normal,
      fontSize: theme.fontSize.sm,
      lineHeight: theme.lineHeight.sm,
    },
    caption2: {
      color: theme.colors.secondary,
      fontWeight: theme.fontWeight.normal,
      fontSize: theme.fontSize.xs,
      lineHeight: theme.lineHeight.xs,
    },
    // LEGACY
    "5xlTitle": {
      color: theme.colors.secondary,
      fontSize: "52px",
      letterSpacing: "0.02em",
      lineHeight: "60px",
      fontWeight: 600,
    },
    "4xlTitle": {
      color: theme.colors.secondary,
      fontSize: "52px",
      letterSpacing: "0.02em",
      lineHeight: "60px",
      fontWeight: 400,
    },
    xxlTitle: {
      color: theme.colors.secondary,
      fontSize: "42px",
      letterSpacing: "0.02em",
      lineHeight: "52px",
      fontWeight: 400,
    },
    lTitle: {
      color: theme.colors.secondary,
      fontSize: "32px",
      letterSpacing: "0.02em",
      lineHeight: "40px",
      fontWeight: 400,
    },
    sTitle: {
      color: theme.colors.secondary,
      fontSize: "22px",
      letterSpacing: "0.02em",
      lineHeight: "30px",
      fontWeight: 400,
    },
    xxsTitle: {
      color: theme.colors.secondary,
      fontSize: "18px",
      letterSpacing: "0.02em",
      lineHeight: "28px",
      fontWeight: 400,
    },
    sectionTitle: {
      color: theme.colors.secondary,
      fontSize: "14px",
      letterSpacing: "0.32em",
      lineHeight: "18px",
      fontWeight: 400,
      textTransform: "uppercase",
    },
    placeholderText: {
      color: theme.colors.secondary_60,
      fontSize: "12px",
      letterSpacing: "0.02em",
      lineHeight: "16px",
      fontWeight: 400,
    },
    link: {
      color: theme.colors.primary,
      fontSize: "12px",
      letterSpacing: "0.02em",
      lineHeight: "16px",
      fontWeight: 600,
    },
    disabledText: {
      color: theme.colors.secondary_60,
      fontSize: "12px",
      letterSpacing: "0.02em",
      lineHeight: "16px",
      fontWeight: 600,
    },
    selectedNavText: {
      color: theme.colors.brand,
      fontSize: "12px",
      letterSpacing: "0.02em",
      lineHeight: "16px",
      fontWeight: 600,
    },
    vizTextDisabled: {
      color: theme.colors.secondary_60,
      fontSize: "10px",
      letterSpacing: "0.02em",
      lineHeight: "15px",
      fontWeight: 400,
    },
    xsInlineLink: {
      color: theme.colors.primary,
      fontSize: "10px",
      letterSpacing: "0.02em",
      lineHeight: "15px",
      fontWeight: 600,
      textDecoration: "underline",
    },
  },
}));
