name: Documentation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [docs, storybook]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Artifacts
        run: |
          if [ "${{ matrix.target }}" == "docs" ]; then
            BASE_PATH='/docs' pnpm run build:doc
            touch ${{ github.workspace }}/apps/docs/dist/.nojekyll
          else
            pnpm run build:storybook
          fi
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ${{ matrix.target == 'docs' && 'apps/docs/dist' || 'storybook-static' }}
          destination_dir: ${{ matrix.target }}
          external_repository: ${{ github.repository_owner }}/next-design-labs.github.io
          publish_branch: master
